name: MindsDB workflow

on:
  push:
  pull_request:
    branches:
      - stable

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1      
        with:          
          filter: '[?runOn==`${{ github.ref }}` || runOn==`always`]'
  test:
    needs: matrix_prep
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    name: Tests
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        #python -m pip install --upgrade pip==21.0.1
        pip install 'pymssql >= 2.1.4'
        pip install boto3
        pip install --no-cache-dir .
        if [ "$INSTALL_RAY" == "install_ray" ]; then
          git clone https://${ACCESS_KEY}@github.com/mindsdb/worker.git;
          cd worker;
          pip install --no-cache-dir .;
          cd ..;
        fi
      shell: bash
      env:
        INSTALL_RAY: ${{ matrix.token }}
        ACCESS_KEY:  ${{ secrets.GH_ACCESS_KEY }}
        mindsdb_github_masterkey: ${{secrets.mindsdb_github_masterkey}}
    - name: Install dependencies Windows
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html;
        fi
      shell: bash
      env:
        CHECK_FOR_UPDATES: False
    - name: Install mindsdb_native/staging if it's not mindsdb/stable
      if: github.ref != 'refs/heads/stable'
      run: |
          pip install git+https://github.com/mindsdb/mindsdb_native.git@staging --upgrade --no-cache-dir
          pip install git+https://github.com/mindsdb/lightwood.git@staging --upgrade --no-cache-dir
    - name: Run integration api and flow tests
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          mkdir -p ~/.ssh/
          echo "$DB_MACHINE_KEY" > ~/.ssh/db_machine
          sudo chmod 600 ~/.ssh/db_machine
          echo "$DB_MACHINE_MS_KEY" > ~/.ssh/db_machine_ms
          sudo chmod 600 ~/.ssh/db_machine_ms
          echo "$DATABASE_CREDENTIALS" > ~/.mindsdb_credentials.json
          sudo chmod 644 ~/.mindsdb_credentials.json

          export USE_EXTERNAL_DB_SERVER="1"

          # HTTP
          echo -e "\n===============\ntest HTTP\n===============\n"
          python tests/integration_tests/flows/test_http.py

          # ClickHouse
          echo -e "\n===============\ntest ClickHouse\n===============\n"
          python tests/integration_tests/flows/test_clickhouse.py

          # MsSQL
          echo -e "\n===============\ntest MsSQL\n===============\n"
          python tests/integration_tests/flows/test_mssql.py


          # MongoDB
          #echo -e "\n===============\ntest MongoDB\n===============\n"
          #python tests/integration_tests/flows/test_mongo.py


          # PostgreSQL
          echo -e "\n===============\ntest PostgreSQL\n===============\n"
          python tests/integration_tests/flows/test_postgres.py


          # MySQL
          echo -e "\n===============\ntest MySQL\n===============\n"
          python tests/integration_tests/flows/test_mysql.py


          # MariaDB
          echo -e "\n===============\ntest MariaDB\n===============\n"
          python tests/integration_tests/flows/test_mariadb.py


          # user flow 1
          echo -e "\n===============\ntest user flow 1\n===============\n"
          python tests/integration_tests/flows/test_user_flow_1.py


          # user flow 2
          echo -e "\n===============\ntest user flow 2\n===============\n"
          python tests/integration_tests/flows/test_user_flow_2.py

          # There are some issues with stopping the ray-based version
          if [ "$INSTALL_RAY" == "not_install_ray" ]; then
            # flow with mistakes
            echo -e "\n===============\nflow with mistakes\n===============\n"
            python tests/integration_tests/flows/test_mistakes.py
          fi
        fi
      shell: bash
      env:
        CHECK_FOR_UPDATES: False
        DB_MACHINE_KEY: ${{secrets.DB_MACHINE_KEY}}
        DB_MACHINE_MS_KEY: ${{secrets.DB_MACHINE_MS_KEY}}
        DATABASE_CREDENTIALS: ${{secrets.DATABASE_CREDENTIALS}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}

  deploy_to_pypi:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/stable' && github.actor != 'mindsdbadmin'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME:  __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist
        twine upload dist/*
    - name: Install latest version from pypi to see that all is working
      run: |
        sleep 20
        pip install mindsdb

  build_amis_packer:
   #TODO: in the future migrate to https://github.com/hashicorp/packer-github-actions, when we can send config as an url
      runs-on: ubuntu-latest
      needs: deploy_to_pypi
      if: github.ref == 'refs/heads/stable' && github.actor != 'mindsdbadmin'
      steps:
      - uses: actions/checkout@v2
      - name: Deploy AMI's
        env:
          ACCESS_KEY:  ${{ secrets.GH_ACCESS_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #NOTE: Send variables to packer build command or var file, because if using env in conf they are not vissible to build
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get install packer
          python deploy_version.py release
          mdb_version=`cat distributions/ver/dist/stable_version.txt`
          export MINDSDB_VERSION="$mdb_version"
          git clone https://${ACCESS_KEY}@github.com/mindsdb/mindsdb_gateway
          cd mindsdb_gateway/deployments
          echo "Building AMIs for $MINDSDB_VERSION"
          sudo packer build -var "mindsdb_version=$MINDSDB_VERSION" -var "acces_key=$ACCESS_KEY" -var "aws_acces_key=$AWS_ACCESS_KEY" -var "aws_secret_key=$AWS_SECRET_KEY" config.json

  deploy_version_file:
    runs-on: ubuntu-latest
    needs: build_amis_packer
    if: github.ref == 'refs/heads/stable' && github.actor != 'mindsdbadmin'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Deploy version files
      run: |
        python deploy_version.py beta

    - name: Sync linux sh installer to s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: 'mindsdb-installer'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'distributions/ver/dist'
        DEST_DIR: 'mindsdb-installer/ver'
